services:
  order-service:
    build: ./app/order-service
    container_name: order-service
    ports:
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
    environment:
      - PORT=${ORDER_SERVICE_PORT}
      - SERVICE_NAME=${ORDER_SERVICE_NAME}
    networks:
      - watchtower-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  tracking-service:
    build: ./app/tracking-service
    container_name: tracking-service
    ports:
      - "${TRACKING_SERVICE_PORT}:${TRACKING_SERVICE_PORT}"
    environment:
      - PORT=${TRACKING_SERVICE_PORT}
      - SERVICE_NAME=${TRACKING_SERVICE_NAME}
    networks:
      - watchtower-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  notification-service:
    build: ./app/notification-service
    container_name: notification-service
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}"
    environment:
      - PORT=${NOTIFICATION_SERVICE_PORT}
      - SERVICE_NAME=${NOTIFICATION_SERVICE_NAME}
    networks:
      - watchtower-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - watchtower-net

  grafana:
    image: grafana/grafana:10.4.6
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - watchtower-net
    depends_on:
      - prometheus

networks:
  watchtower-net:
    driver: bridge
