name: Deploy Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Get the code from repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js to run tests
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        working-directory: dev-ops/DeployReady/app
        run: npm install

      # Run tests (pipeline stops if this fails)
      - name: Run tests
        working-directory: dev-ops/DeployReady/app
        run: npm test

      # Login to GitHub Container Registry
      - name: Login to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build Docker image
      - name: Build image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/deployready-app:${{ github.sha }} dev-ops/DeployReady

      # Push Docker image
      - name: Push image
        run: docker push ghcr.io/${{ github.repository_owner }}/deployready-app:${{ github.sha }}

      # Deploy the new Docker image to the EC2 server
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker pull ghcr.io/${{ github.repository_owner }}/deployready-app:${{ github.sha }}

            docker stop deployready-app || true
            docker rm deployready-app || true

            docker run -d \
              --name deployready-app \
              --restart unless-stopped \
              -e PORT=3000 \
              -p 80:3000 \
              ghcr.io/${{ github.repository_owner }}/deployready-app:${{ github.sha }}
